const GeoLayout smw_mario_002_switch_opt0_001_switch_opt0_000_switch_opt0_000_switch_001_opt8_switch_face1_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, smw_mario_002_switch_option1_headfall_mesh_layer_1_mat_override_face_1___eye_half_v3_001_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout smw_mario_002_switch_opt0_001_switch_opt0_000_switch_opt0_000_switch_001_opt8_switch_face1_opt2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, smw_mario_002_switch_option1_headfall_mesh_layer_1_mat_override_face_2___eye_closed_v3_001_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout smw_mario_002_switch_opt0_001_switch_opt0_000_switch_opt0_000_switch_001_opt8_switch_face1_opt3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, smw_mario_002_switch_option1_headfall_mesh_layer_1_mat_override_face_2___eye_closed_v3_001_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout smw_mario_002_switch_opt0_001_switch_opt0_000_switch_opt0_000_switch_001_opt8_switch_face1_opt4[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, smw_mario_002_switch_option1_headfall_mesh_layer_1_mat_override_face_2___eye_closed_v3_001_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout smw_mario_002_switch_opt0_001_switch_opt0_000_switch_opt0_000_switch_001_opt8_switch_face1_opt5[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, smw_mario_002_switch_option1_headfall_mesh_layer_1_mat_override_face_2___eye_closed_v3_001_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout smw_mario_002_switch_opt0_001_switch_opt0_000_switch_opt0_000_switch_001_opt8_switch_face1_opt6[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, smw_mario_002_switch_option1_headfall_mesh_layer_1_mat_override_face_2___eye_closed_v3_001_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout smw_mario_002_switch_opt0_001_switch_opt0_000_switch_opt0_000_switch_001_opt8_switch_face1_opt7[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, smw_mario_002_switch_option1_headfall_mesh_layer_1_mat_override_face_7___eye_X_v3_001_3),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout smw_mario_head_faal[] = {
	GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 4, 0, 0, 0, 0),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
		GEO_OPEN_NODE(),
			GEO_NODE_START(),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, smw_mario_002_switch_option1_headfall_mesh_layer_1),
			GEO_CLOSE_NODE(),
			GEO_BRANCH(1, smw_mario_002_switch_opt0_001_switch_opt0_000_switch_opt0_000_switch_001_opt8_switch_face1_opt1),
			GEO_BRANCH(1, smw_mario_002_switch_opt0_001_switch_opt0_000_switch_opt0_000_switch_001_opt8_switch_face1_opt2),
			GEO_BRANCH(1, smw_mario_002_switch_opt0_001_switch_opt0_000_switch_opt0_000_switch_001_opt8_switch_face1_opt3),
			GEO_BRANCH(1, smw_mario_002_switch_opt0_001_switch_opt0_000_switch_opt0_000_switch_001_opt8_switch_face1_opt4),
			GEO_BRANCH(1, smw_mario_002_switch_opt0_001_switch_opt0_000_switch_opt0_000_switch_001_opt8_switch_face1_opt5),
			GEO_BRANCH(1, smw_mario_002_switch_opt0_001_switch_opt0_000_switch_opt0_000_switch_001_opt8_switch_face1_opt6),
			GEO_BRANCH(1, smw_mario_002_switch_opt0_001_switch_opt0_000_switch_opt0_000_switch_001_opt8_switch_face1_opt7),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout smw_mario_002_switch_opt0_001_switch_opt0_000_switch_opt0_000_switch_001_opt9_switch_face2_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, smw_mario_002_switch_option2_headcrouch_mesh_layer_1_mat_override_face_1___eye_half_v3_001_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout smw_mario_002_switch_opt0_001_switch_opt0_000_switch_opt0_000_switch_001_opt9_switch_face2_opt2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, smw_mario_002_switch_option2_headcrouch_mesh_layer_1_mat_override_face_2___eye_closed_v3_001_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout smw_mario_002_switch_opt0_001_switch_opt0_000_switch_opt0_000_switch_001_opt9_switch_face2_opt3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, smw_mario_002_switch_option2_headcrouch_mesh_layer_1_mat_override_face_2___eye_closed_v3_001_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout smw_mario_002_switch_opt0_001_switch_opt0_000_switch_opt0_000_switch_001_opt9_switch_face2_opt4[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, smw_mario_002_switch_option2_headcrouch_mesh_layer_1_mat_override_face_2___eye_closed_v3_001_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout smw_mario_002_switch_opt0_001_switch_opt0_000_switch_opt0_000_switch_001_opt9_switch_face2_opt5[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, smw_mario_002_switch_option2_headcrouch_mesh_layer_1_mat_override_face_2___eye_closed_v3_001_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout smw_mario_002_switch_opt0_001_switch_opt0_000_switch_opt0_000_switch_001_opt9_switch_face2_opt6[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, smw_mario_002_switch_option2_headcrouch_mesh_layer_1_mat_override_face_2___eye_closed_v3_001_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout smw_mario_002_switch_opt0_001_switch_opt0_000_switch_opt0_000_switch_001_opt9_switch_face2_opt7[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, smw_mario_002_switch_option2_headcrouch_mesh_layer_1_mat_override_face_7___eye_X_v3_001_3),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout smw_mario_head_crouch[] = {
	GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 4, 0, 0, 0, 0),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
		GEO_OPEN_NODE(),
			GEO_NODE_START(),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, smw_mario_002_switch_option2_headcrouch_mesh_layer_1),
			GEO_CLOSE_NODE(),
			GEO_BRANCH(1, smw_mario_002_switch_opt0_001_switch_opt0_000_switch_opt0_000_switch_001_opt9_switch_face2_opt1),
			GEO_BRANCH(1, smw_mario_002_switch_opt0_001_switch_opt0_000_switch_opt0_000_switch_001_opt9_switch_face2_opt2),
			GEO_BRANCH(1, smw_mario_002_switch_opt0_001_switch_opt0_000_switch_opt0_000_switch_001_opt9_switch_face2_opt3),
			GEO_BRANCH(1, smw_mario_002_switch_opt0_001_switch_opt0_000_switch_opt0_000_switch_001_opt9_switch_face2_opt4),
			GEO_BRANCH(1, smw_mario_002_switch_opt0_001_switch_opt0_000_switch_opt0_000_switch_001_opt9_switch_face2_opt5),
			GEO_BRANCH(1, smw_mario_002_switch_opt0_001_switch_opt0_000_switch_opt0_000_switch_001_opt9_switch_face2_opt6),
			GEO_BRANCH(1, smw_mario_002_switch_opt0_001_switch_opt0_000_switch_opt0_000_switch_001_opt9_switch_face2_opt7),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout smw_mario_002_switch_opt0_001_switch_opt0_000_switch_opt1_switch_face_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, smw_mario_002_switch_option_head__no_cap__mesh_layer_1_mat_override_face_1___eye_half_v3_001_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout smw_mario_002_switch_opt0_001_switch_opt0_000_switch_opt1_switch_face_opt2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, smw_mario_002_switch_option_head__no_cap__mesh_layer_1_mat_override_face_2___eye_closed_v3_001_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout smw_mario_002_switch_opt0_001_switch_opt0_000_switch_opt1_switch_face_opt3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, smw_mario_002_switch_option_head__no_cap__mesh_layer_1_mat_override_face_2___eye_closed_v3_001_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout smw_mario_002_switch_opt0_001_switch_opt0_000_switch_opt1_switch_face_opt4[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, smw_mario_002_switch_option_head__no_cap__mesh_layer_1_mat_override_face_2___eye_closed_v3_001_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout smw_mario_002_switch_opt0_001_switch_opt0_000_switch_opt1_switch_face_opt5[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, smw_mario_002_switch_option_head__no_cap__mesh_layer_1_mat_override_face_2___eye_closed_v3_001_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout smw_mario_002_switch_opt0_001_switch_opt0_000_switch_opt1_switch_face_opt6[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, smw_mario_002_switch_option_head__no_cap__mesh_layer_1_mat_override_face_2___eye_closed_v3_001_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout smw_mario_002_switch_opt0_001_switch_opt0_000_switch_opt1_switch_face_opt7[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, smw_mario_002_switch_option_head__no_cap__mesh_layer_1_mat_override_face_7___eye_X_v3_001_3),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout smw_mario_armature_002_switch_option_002[] = {
	GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 4, 0, 0, 0, 0),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
		GEO_OPEN_NODE(),
			GEO_NODE_START(),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, smw_mario_002_switch_option_head__no_cap__mesh_layer_1),
			GEO_CLOSE_NODE(),
			GEO_BRANCH(1, smw_mario_002_switch_opt0_001_switch_opt0_000_switch_opt1_switch_face_opt1),
			GEO_BRANCH(1, smw_mario_002_switch_opt0_001_switch_opt0_000_switch_opt1_switch_face_opt2),
			GEO_BRANCH(1, smw_mario_002_switch_opt0_001_switch_opt0_000_switch_opt1_switch_face_opt3),
			GEO_BRANCH(1, smw_mario_002_switch_opt0_001_switch_opt0_000_switch_opt1_switch_face_opt4),
			GEO_BRANCH(1, smw_mario_002_switch_opt0_001_switch_opt0_000_switch_opt1_switch_face_opt5),
			GEO_BRANCH(1, smw_mario_002_switch_opt0_001_switch_opt0_000_switch_opt1_switch_face_opt6),
			GEO_BRANCH(1, smw_mario_002_switch_opt0_001_switch_opt0_000_switch_opt1_switch_face_opt7),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout smw_mario_right_hand_open_armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, smw_mario_002_switch_option_right_hand_open_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout smw_mario_left_hand_open_armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, smw_mario_002_switch_option_left_hand_open_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout smw_mario_left_hand_peace_armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, smw_mario_004_switch_option_left_hand_peace_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout smw_mario_left_hand_cap_armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, smw_mario_005_switch_option_left_hand_cap_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout smw_mario_left_hand_wing_cap_armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, smw_mario_006_switch_option_left_hand_wing_cap_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_TRANSPARENT, smw_mario_006_switch_option_left_hand_wing_cap_wings_mesh_layer_5),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout smw_mario_002_switchw_SMALL_Head_Fall[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
		GEO_OPEN_NODE(),
			GEO_NODE_START(),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, smw_mario_002_switchw_002_switch_option1wy_headfally_mesh_layer_1),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout smw_mario_002_switchw_SMALL_head_crouch[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
		GEO_OPEN_NODE(),
			GEO_NODE_START(),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, smw_mario_002_switchw_002_switch_option2h_headcrouchh_mesh_layer_1),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout smw_mario_002_switchw_SMALL_head_dead[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
		GEO_OPEN_NODE(),
			GEO_NODE_START(),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, smw_mario_002_switchw_002_switch_option1ww_headdeadw_mesh_layer_1),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout smw_mario_002_switch_opt1_001_switchw_opt1_jump_smw_mario_002_switchw_SMALL_Head_Fall[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
		GEO_OPEN_NODE(),
			GEO_NODE_START(),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, smw_mario_002_switchw_002_switch_option1wy_headfally_mesh_layer_1),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout smw_mario_002_switch_opt1_001_switchw_opt1_jump_smw_mario_002_switchw_SMALL_head_crouch[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
		GEO_OPEN_NODE(),
			GEO_NODE_START(),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, smw_mario_002_switchw_002_switch_option2h_headcrouchh_mesh_layer_1),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout smw_mario_002_switch_opt1_001_switchw_opt1_jump_smw_mario_002_switchw_SMALL_head_dead[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
		GEO_OPEN_NODE(),
			GEO_NODE_START(),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, smw_mario_002_switchw_002_switch_option1ww_headdeadw_mesh_layer_1),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout smw_mario_002_switch_opt1_001_switchw_opt1_jump_smw_mario_right_hand_open_armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, smw_mario_002_switch_option_right_hand_open_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout smw_mario_002_switch_opt1_001_switchw_opt1_jump_smw_mario_left_hand_open_armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, smw_mario_002_switch_option_left_hand_open_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout smw_mario_002_switch_opt1_001_switchw_opt1_jump_smw_mario_left_hand_peace_armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, smw_mario_004_switch_option_left_hand_peace_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout smw_mario_002_switch_opt1_001_switchw_opt1_jump_smw_mario_left_hand_peace_armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, smw_mario_004_switch_option_left_hand_peace_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout smw_mario_002_switch_opt1_001_switchw_opt1_jump_smw_mario_left_hand_peace_armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, smw_mario_004_switch_option_left_hand_peace_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout smw_mario_002_switch_opt1_001_switchw_opt1_000_switchw_opt0_000_switch_001w_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, smw_mario_002_switchw_000_displaylistw_mesh_layer_1_mat_override_face_1___eye_half_v3_002_0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout smw_mario_002_switch_opt1_001_switchw_opt1_000_switchw_opt0_000_switch_001w_opt2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, smw_mario_002_switchw_000_displaylistw_mesh_layer_1_mat_override_face_2___eye_closed_v3_002_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout smw_mario_002_switch_opt1_001_switchw_opt1_000_switchw_opt0_000_switch_001w_opt3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, smw_mario_002_switchw_000_displaylistw_mesh_layer_1_mat_override_face_2___eye_closed_v3_002_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout smw_mario_002_switch_opt1_001_switchw_opt1_000_switchw_opt0_000_switch_001w_opt4[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, smw_mario_002_switchw_000_displaylistw_mesh_layer_1_mat_override_face_2___eye_closed_v3_002_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout smw_mario_002_switch_opt1_001_switchw_opt1_000_switchw_opt0_000_switch_001w_opt5[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, smw_mario_002_switchw_000_displaylistw_mesh_layer_1_mat_override_face_2___eye_closed_v3_002_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout smw_mario_002_switch_opt1_001_switchw_opt1_000_switchw_opt0_000_switch_001w_opt6[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, smw_mario_002_switchw_000_displaylistw_mesh_layer_1_mat_override_face_2___eye_closed_v3_002_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout smw_mario_002_switch_opt1_001_switchw_opt1_000_switchw_opt0_000_switch_001w_opt7[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, smw_mario_002_switchw_000_displaylistw_mesh_layer_1_mat_override_face_7___eye_X_v3_002_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout smw_mario_002_switch_opt1_001_switchw_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, smw_mario_002_switchw_000_offsetw_mesh_layer_1),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, smw_mario_002_switchw_000_offset_001w_skinned_mesh_layer_1),
				GEO_ASM(0, geo_move_mario_part_from_parent),
				GEO_ASM(0, geo_mario_tilt_torso),
				GEO_SHADOW(1, 0, 100),
				GEO_OPEN_NODE(),
					GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 10, 3, 0, 0, 0, -1),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, smw_mario_002_switchw_000_offset_001w_mesh_layer_1),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 77, 0, 0, NULL),
							GEO_OPEN_NODE(),
								GEO_ASM(0, geo_mario_head_rotation),
								GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
								GEO_OPEN_NODE(),
									GEO_SWITCH_CASE(0, geo_switch_mario_cap_on_off),
									GEO_OPEN_NODE(),
										GEO_NODE_START(),
										GEO_OPEN_NODE(),
											GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
											GEO_OPEN_NODE(),
												GEO_NODE_START(),
												GEO_OPEN_NODE(),
													GEO_DISPLAY_LIST(LAYER_TRANSPARENT, smw_mario_002_switchw_000_displaylistw_mesh_layer_1),
												GEO_CLOSE_NODE(),
												GEO_BRANCH(1, smw_mario_002_switch_opt1_001_switchw_opt1_000_switchw_opt0_000_switch_001w_opt1),
												GEO_BRANCH(1, smw_mario_002_switch_opt1_001_switchw_opt1_000_switchw_opt0_000_switch_001w_opt2),
												GEO_BRANCH(1, smw_mario_002_switch_opt1_001_switchw_opt1_000_switchw_opt0_000_switch_001w_opt3),
												GEO_BRANCH(1, smw_mario_002_switch_opt1_001_switchw_opt1_000_switchw_opt0_000_switch_001w_opt4),
												GEO_BRANCH(1, smw_mario_002_switch_opt1_001_switchw_opt1_000_switchw_opt0_000_switch_001w_opt5),
												GEO_BRANCH(1, smw_mario_002_switch_opt1_001_switchw_opt1_000_switchw_opt0_000_switch_001w_opt6),
												GEO_BRANCH(1, smw_mario_002_switch_opt1_001_switchw_opt1_000_switchw_opt0_000_switch_001w_opt7),
												GEO_BRANCH(1, smw_mario_002_switch_opt1_001_switchw_opt1_jump_smw_mario_002_switchw_SMALL_Head_Fall),
												GEO_BRANCH(1, smw_mario_002_switch_opt1_001_switchw_opt1_jump_smw_mario_002_switchw_SMALL_head_crouch),
												GEO_BRANCH(1, smw_mario_002_switch_opt1_001_switchw_opt1_jump_smw_mario_002_switchw_SMALL_head_dead),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
									GEO_TRANSLATE_ROTATE(LAYER_FORCE, 210, -51, -126, 15, -33, -133),
									GEO_OPEN_NODE(),
										GEO_ASM(0, geo_mario_rotate_wing_cap_wings),
										GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
										GEO_OPEN_NODE(),
											GEO_DISPLAY_LIST(LAYER_TRANSPARENT, smw_mario_002_switchw_000_displaylist_001w_mesh_layer_5),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
									GEO_TRANSLATE_ROTATE(LAYER_FORCE, 210, -51, 126, -15, 33, -133),
									GEO_OPEN_NODE(),
										GEO_ASM(1, geo_mario_rotate_wing_cap_wings),
										GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
										GEO_OPEN_NODE(),
											GEO_DISPLAY_LIST(LAYER_TRANSPARENT, smw_mario_002_switchw_000_displaylist_002w_mesh_layer_5),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 54, -10, 60, NULL),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, smw_mario_002_switchw_000_offset_003_mesh_layer_1),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(LAYER_TRANSPARENT, smw_mario_002_switchw_000_offset_004_skinned_mesh_layer_1),
									GEO_ANIMATED_PART(LAYER_TRANSPARENT, 56, 0, 0, smw_mario_002_switchw_000_offset_004_mesh_layer_1),
									GEO_OPEN_NODE(),
										GEO_SWITCH_CASE(1, geo_switch_mario_hand),
										GEO_OPEN_NODE(),
											GEO_NODE_START(),
											GEO_OPEN_NODE(),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 42, 0, 0, NULL),
												GEO_OPEN_NODE(),
													GEO_ASM(1, geo_mario_hand_foot_scaler),
													GEO_SCALE(LAYER_FORCE, 65536),
													GEO_OPEN_NODE(),
														GEO_DISPLAY_LIST(LAYER_TRANSPARENT, smw_mario_002_switchw_000_displaylist_003_mesh_layer_1),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
											GEO_BRANCH(1, smw_mario_002_switch_opt1_001_switchw_opt1_jump_smw_mario_right_hand_open_armature),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 55, -10, -60, NULL),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, smw_mario_002_switchw_000_offset_006w_mesh_layer_1),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(LAYER_TRANSPARENT, smw_mario_002_switchw_000_offset_007w_skinned_mesh_layer_1),
									GEO_ANIMATED_PART(LAYER_TRANSPARENT, 56, 0, 0, smw_mario_002_switchw_000_offset_007w_mesh_layer_1),
									GEO_OPEN_NODE(),
										GEO_SWITCH_CASE(0, geo_switch_mario_hand),
										GEO_OPEN_NODE(),
											GEO_NODE_START(),
											GEO_OPEN_NODE(),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 42, 0, 0, NULL),
												GEO_OPEN_NODE(),
													GEO_ASM(0, geo_mario_hand_foot_scaler),
													GEO_SCALE(LAYER_FORCE, 65536),
													GEO_OPEN_NODE(),
														GEO_DISPLAY_LIST(LAYER_TRANSPARENT, smw_mario_002_switchw_000_displaylist_004w_mesh_layer_1),
													GEO_CLOSE_NODE(),
													GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
											GEO_BRANCH(1, smw_mario_002_switch_opt1_001_switchw_opt1_jump_smw_mario_left_hand_open_armature),
											GEO_BRANCH(1, smw_mario_002_switch_opt1_001_switchw_opt1_jump_smw_mario_left_hand_peace_armature),
											GEO_BRANCH(1, smw_mario_002_switch_opt1_001_switchw_opt1_jump_smw_mario_left_hand_peace_armature),
											GEO_BRANCH(1, smw_mario_002_switch_opt1_001_switchw_opt1_jump_smw_mario_left_hand_peace_armature),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, smw_mario_002_switchw_000_offset_009w_skinned_mesh_layer_1),
				GEO_ANIMATED_PART(LAYER_OPAQUE, -16, -5, 42, NULL),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, smw_mario_002_switchw_000_offset_009w_mesh_layer_1),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 15, 0, 0, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 9, 4, 0, smw_mario_002_switchw_000_offset_011w_mesh_layer_1),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, smw_mario_002_switchw_000_offset_012w_skinned_mesh_layer_1),
				GEO_ANIMATED_PART(LAYER_OPAQUE, -16, -5, -42, NULL),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, smw_mario_002_switchw_000_offset_012w_mesh_layer_1),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 15, 0, 0, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 9, 4, 0, NULL),
							GEO_OPEN_NODE(),
								GEO_ASM(2, geo_mario_hand_foot_scaler),
								GEO_SCALE(LAYER_FORCE, 65536),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(LAYER_TRANSPARENT, smw_mario_002_switchw_000_displaylist_005w_mesh_layer_1),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout smw_mario_002_switch_opt1_001_switchw_opt0_000_switchw_opt0_000_switch_001w_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, smw_mario_002_switchw_000_displaylistw_mesh_layer_1_mat_override_face_1___eye_half_v3_002_0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout smw_mario_002_switch_opt1_001_switchw_opt0_000_switchw_opt0_000_switch_001w_opt2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, smw_mario_002_switchw_000_displaylistw_mesh_layer_1_mat_override_face_2___eye_closed_v3_002_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout smw_mario_002_switch_opt1_001_switchw_opt0_000_switchw_opt0_000_switch_001w_opt3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, smw_mario_002_switchw_000_displaylistw_mesh_layer_1_mat_override_face_2___eye_closed_v3_002_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout smw_mario_002_switch_opt1_001_switchw_opt0_000_switchw_opt0_000_switch_001w_opt4[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, smw_mario_002_switchw_000_displaylistw_mesh_layer_1_mat_override_face_2___eye_closed_v3_002_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout smw_mario_002_switch_opt1_001_switchw_opt0_000_switchw_opt0_000_switch_001w_opt5[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, smw_mario_002_switchw_000_displaylistw_mesh_layer_1_mat_override_face_2___eye_closed_v3_002_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout smw_mario_002_switch_opt1_001_switchw_opt0_000_switchw_opt0_000_switch_001w_opt6[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, smw_mario_002_switchw_000_displaylistw_mesh_layer_1_mat_override_face_2___eye_closed_v3_002_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout smw_mario_002_switch_opt1_001_switchw_opt0_000_switchw_opt0_000_switch_001w_opt7[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, smw_mario_002_switchw_000_displaylistw_mesh_layer_1_mat_override_face_7___eye_X_v3_002_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout smw_mario_SMALL_Mario[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(0, geo_switch_mario_cap_effect),
		GEO_OPEN_NODE(),
			GEO_NODE_START(),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, smw_mario_002_switchw_000_offsetw_mesh_layer_1),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_OPAQUE, smw_mario_002_switchw_000_offset_001w_skinned_mesh_layer_1),
						GEO_ASM(0, geo_move_mario_part_from_parent),
						GEO_ASM(0, geo_mario_tilt_torso),
						GEO_SHADOW(1, 0, 100),
						GEO_OPEN_NODE(),
							GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 10, 3, 0, 0, 0, -1),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, smw_mario_002_switchw_000_offset_001w_mesh_layer_1),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 77, 0, 0, NULL),
									GEO_OPEN_NODE(),
										GEO_ASM(0, geo_mario_head_rotation),
										GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
										GEO_OPEN_NODE(),
											GEO_SWITCH_CASE(0, geo_switch_mario_cap_on_off),
											GEO_OPEN_NODE(),
												GEO_NODE_START(),
												GEO_OPEN_NODE(),
													GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
													GEO_OPEN_NODE(),
														GEO_NODE_START(),
														GEO_OPEN_NODE(),
															GEO_DISPLAY_LIST(LAYER_OPAQUE, smw_mario_002_switchw_000_displaylistw_mesh_layer_1),
														GEO_CLOSE_NODE(),
														GEO_BRANCH(1, smw_mario_002_switch_opt1_001_switchw_opt0_000_switchw_opt0_000_switch_001w_opt1),
														GEO_BRANCH(1, smw_mario_002_switch_opt1_001_switchw_opt0_000_switchw_opt0_000_switch_001w_opt2),
														GEO_BRANCH(1, smw_mario_002_switch_opt1_001_switchw_opt0_000_switchw_opt0_000_switch_001w_opt3),
														GEO_BRANCH(1, smw_mario_002_switch_opt1_001_switchw_opt0_000_switchw_opt0_000_switch_001w_opt4),
														GEO_BRANCH(1, smw_mario_002_switch_opt1_001_switchw_opt0_000_switchw_opt0_000_switch_001w_opt5),
														GEO_BRANCH(1, smw_mario_002_switch_opt1_001_switchw_opt0_000_switchw_opt0_000_switch_001w_opt6),
														GEO_BRANCH(1, smw_mario_002_switch_opt1_001_switchw_opt0_000_switchw_opt0_000_switch_001w_opt7),
														GEO_BRANCH(1, smw_mario_002_switchw_SMALL_Head_Fall),
														GEO_BRANCH(1, smw_mario_002_switchw_SMALL_head_crouch),
														GEO_BRANCH(1, smw_mario_002_switchw_SMALL_head_dead),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
											GEO_TRANSLATE_ROTATE(LAYER_FORCE, 210, -51, -126, 15, -33, -133),
											GEO_OPEN_NODE(),
												GEO_ASM(0, geo_mario_rotate_wing_cap_wings),
												GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
												GEO_OPEN_NODE(),
													GEO_DISPLAY_LIST(LAYER_TRANSPARENT, smw_mario_002_switchw_000_displaylist_001w_mesh_layer_5),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
											GEO_TRANSLATE_ROTATE(LAYER_FORCE, 210, -51, 126, -15, 33, -133),
											GEO_OPEN_NODE(),
												GEO_ASM(1, geo_mario_rotate_wing_cap_wings),
												GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
												GEO_OPEN_NODE(),
													GEO_DISPLAY_LIST(LAYER_TRANSPARENT, smw_mario_002_switchw_000_displaylist_002w_mesh_layer_5),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 54, -10, 60, NULL),
									GEO_OPEN_NODE(),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, smw_mario_002_switchw_000_offset_003_mesh_layer_1),
										GEO_OPEN_NODE(),
											GEO_DISPLAY_LIST(LAYER_OPAQUE, smw_mario_002_switchw_000_offset_004_skinned_mesh_layer_1),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 56, 0, 0, smw_mario_002_switchw_000_offset_004_mesh_layer_1),
											GEO_OPEN_NODE(),
												GEO_SWITCH_CASE(1, geo_switch_mario_hand),
												GEO_OPEN_NODE(),
													GEO_NODE_START(),
													GEO_OPEN_NODE(),
														GEO_ANIMATED_PART(LAYER_OPAQUE, 42, 0, 0, NULL),
														GEO_OPEN_NODE(),
															GEO_ASM(1, geo_mario_hand_foot_scaler),
															GEO_SCALE(LAYER_FORCE, 65536),
															GEO_OPEN_NODE(),
																GEO_DISPLAY_LIST(LAYER_OPAQUE, smw_mario_002_switchw_000_displaylist_003_mesh_layer_1),
															GEO_CLOSE_NODE(),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
													GEO_BRANCH(1, smw_mario_right_hand_open_armature),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 55, -10, -60, NULL),
									GEO_OPEN_NODE(),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, smw_mario_002_switchw_000_offset_006w_mesh_layer_1),
										GEO_OPEN_NODE(),
											GEO_DISPLAY_LIST(LAYER_OPAQUE, smw_mario_002_switchw_000_offset_007w_skinned_mesh_layer_1),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 56, 0, 0, smw_mario_002_switchw_000_offset_007w_mesh_layer_1),
											GEO_OPEN_NODE(),
												GEO_SWITCH_CASE(0, geo_switch_mario_hand),
												GEO_OPEN_NODE(),
													GEO_NODE_START(),
													GEO_OPEN_NODE(),
														GEO_ANIMATED_PART(LAYER_OPAQUE, 42, 0, 0, NULL),
														GEO_OPEN_NODE(),
															GEO_ASM(0, geo_mario_hand_foot_scaler),
															GEO_SCALE(LAYER_FORCE, 65536),
															GEO_OPEN_NODE(),
																GEO_DISPLAY_LIST(LAYER_OPAQUE, smw_mario_002_switchw_000_displaylist_004w_mesh_layer_1),
															GEO_CLOSE_NODE(),
															GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
													GEO_BRANCH(1, smw_mario_left_hand_open_armature),
													GEO_BRANCH(1, smw_mario_left_hand_peace_armature),
													GEO_BRANCH(1, smw_mario_left_hand_peace_armature),
													GEO_BRANCH(1, smw_mario_left_hand_peace_armature),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_DISPLAY_LIST(LAYER_OPAQUE, smw_mario_002_switchw_000_offset_009w_skinned_mesh_layer_1),
						GEO_ANIMATED_PART(LAYER_OPAQUE, -16, -5, 42, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, smw_mario_002_switchw_000_offset_009w_mesh_layer_1),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 15, 0, 0, NULL),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 9, 4, 0, smw_mario_002_switchw_000_offset_011w_mesh_layer_1),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_DISPLAY_LIST(LAYER_OPAQUE, smw_mario_002_switchw_000_offset_012w_skinned_mesh_layer_1),
						GEO_ANIMATED_PART(LAYER_OPAQUE, -16, -5, -42, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, smw_mario_002_switchw_000_offset_012w_mesh_layer_1),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 15, 0, 0, NULL),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 9, 4, 0, NULL),
									GEO_OPEN_NODE(),
										GEO_ASM(2, geo_mario_hand_foot_scaler),
										GEO_SCALE(LAYER_FORCE, 65536),
										GEO_OPEN_NODE(),
											GEO_DISPLAY_LIST(LAYER_OPAQUE, smw_mario_002_switchw_000_displaylist_005w_mesh_layer_1),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
			GEO_BRANCH(1, smw_mario_002_switch_opt1_001_switchw_opt1),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout smw_mario_002_switch_opt0_001_switch_opt1_000_switch_opt0_000_switch_001_opt8_switch_face1_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, smw_mario_002_switch_option1_headfall_mesh_layer_1_mat_override_face_1___eye_half_v3_001_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout smw_mario_002_switch_opt0_001_switch_opt1_000_switch_opt0_000_switch_001_opt8_switch_face1_opt2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, smw_mario_002_switch_option1_headfall_mesh_layer_1_mat_override_face_2___eye_closed_v3_001_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout smw_mario_002_switch_opt0_001_switch_opt1_000_switch_opt0_000_switch_001_opt8_switch_face1_opt3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, smw_mario_002_switch_option1_headfall_mesh_layer_1_mat_override_face_2___eye_closed_v3_001_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout smw_mario_002_switch_opt0_001_switch_opt1_000_switch_opt0_000_switch_001_opt8_switch_face1_opt4[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, smw_mario_002_switch_option1_headfall_mesh_layer_1_mat_override_face_2___eye_closed_v3_001_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout smw_mario_002_switch_opt0_001_switch_opt1_000_switch_opt0_000_switch_001_opt8_switch_face1_opt5[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, smw_mario_002_switch_option1_headfall_mesh_layer_1_mat_override_face_2___eye_closed_v3_001_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout smw_mario_002_switch_opt0_001_switch_opt1_000_switch_opt0_000_switch_001_opt8_switch_face1_opt6[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, smw_mario_002_switch_option1_headfall_mesh_layer_1_mat_override_face_2___eye_closed_v3_001_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout smw_mario_002_switch_opt0_001_switch_opt1_000_switch_opt0_000_switch_001_opt8_switch_face1_opt7[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, smw_mario_002_switch_option1_headfall_mesh_layer_1_mat_override_face_7___eye_X_v3_001_3),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout smw_mario_002_switch_opt0_001_switch_opt1_jump_smw_mario_head_faal[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 4, 0, 0, 0, 0),
		GEO_OPEN_NODE(),
			GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
			GEO_OPEN_NODE(),
				GEO_NODE_START(),
				GEO_OPEN_NODE(),
					GEO_DISPLAY_LIST(LAYER_TRANSPARENT, smw_mario_002_switch_option1_headfall_mesh_layer_1),
				GEO_CLOSE_NODE(),
				GEO_BRANCH(1, smw_mario_002_switch_opt0_001_switch_opt1_000_switch_opt0_000_switch_001_opt8_switch_face1_opt1),
				GEO_BRANCH(1, smw_mario_002_switch_opt0_001_switch_opt1_000_switch_opt0_000_switch_001_opt8_switch_face1_opt2),
				GEO_BRANCH(1, smw_mario_002_switch_opt0_001_switch_opt1_000_switch_opt0_000_switch_001_opt8_switch_face1_opt3),
				GEO_BRANCH(1, smw_mario_002_switch_opt0_001_switch_opt1_000_switch_opt0_000_switch_001_opt8_switch_face1_opt4),
				GEO_BRANCH(1, smw_mario_002_switch_opt0_001_switch_opt1_000_switch_opt0_000_switch_001_opt8_switch_face1_opt5),
				GEO_BRANCH(1, smw_mario_002_switch_opt0_001_switch_opt1_000_switch_opt0_000_switch_001_opt8_switch_face1_opt6),
				GEO_BRANCH(1, smw_mario_002_switch_opt0_001_switch_opt1_000_switch_opt0_000_switch_001_opt8_switch_face1_opt7),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout smw_mario_002_switch_opt0_001_switch_opt1_000_switch_opt0_000_switch_001_opt9_switch_face2_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, smw_mario_002_switch_option2_headcrouch_mesh_layer_1_mat_override_face_1___eye_half_v3_001_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout smw_mario_002_switch_opt0_001_switch_opt1_000_switch_opt0_000_switch_001_opt9_switch_face2_opt2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, smw_mario_002_switch_option2_headcrouch_mesh_layer_1_mat_override_face_2___eye_closed_v3_001_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout smw_mario_002_switch_opt0_001_switch_opt1_000_switch_opt0_000_switch_001_opt9_switch_face2_opt3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, smw_mario_002_switch_option2_headcrouch_mesh_layer_1_mat_override_face_2___eye_closed_v3_001_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout smw_mario_002_switch_opt0_001_switch_opt1_000_switch_opt0_000_switch_001_opt9_switch_face2_opt4[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, smw_mario_002_switch_option2_headcrouch_mesh_layer_1_mat_override_face_2___eye_closed_v3_001_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout smw_mario_002_switch_opt0_001_switch_opt1_000_switch_opt0_000_switch_001_opt9_switch_face2_opt5[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, smw_mario_002_switch_option2_headcrouch_mesh_layer_1_mat_override_face_2___eye_closed_v3_001_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout smw_mario_002_switch_opt0_001_switch_opt1_000_switch_opt0_000_switch_001_opt9_switch_face2_opt6[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, smw_mario_002_switch_option2_headcrouch_mesh_layer_1_mat_override_face_2___eye_closed_v3_001_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout smw_mario_002_switch_opt0_001_switch_opt1_000_switch_opt0_000_switch_001_opt9_switch_face2_opt7[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, smw_mario_002_switch_option2_headcrouch_mesh_layer_1_mat_override_face_7___eye_X_v3_001_3),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout smw_mario_002_switch_opt0_001_switch_opt1_jump_smw_mario_head_crouch[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 4, 0, 0, 0, 0),
		GEO_OPEN_NODE(),
			GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
			GEO_OPEN_NODE(),
				GEO_NODE_START(),
				GEO_OPEN_NODE(),
					GEO_DISPLAY_LIST(LAYER_TRANSPARENT, smw_mario_002_switch_option2_headcrouch_mesh_layer_1),
				GEO_CLOSE_NODE(),
				GEO_BRANCH(1, smw_mario_002_switch_opt0_001_switch_opt1_000_switch_opt0_000_switch_001_opt9_switch_face2_opt1),
				GEO_BRANCH(1, smw_mario_002_switch_opt0_001_switch_opt1_000_switch_opt0_000_switch_001_opt9_switch_face2_opt2),
				GEO_BRANCH(1, smw_mario_002_switch_opt0_001_switch_opt1_000_switch_opt0_000_switch_001_opt9_switch_face2_opt3),
				GEO_BRANCH(1, smw_mario_002_switch_opt0_001_switch_opt1_000_switch_opt0_000_switch_001_opt9_switch_face2_opt4),
				GEO_BRANCH(1, smw_mario_002_switch_opt0_001_switch_opt1_000_switch_opt0_000_switch_001_opt9_switch_face2_opt5),
				GEO_BRANCH(1, smw_mario_002_switch_opt0_001_switch_opt1_000_switch_opt0_000_switch_001_opt9_switch_face2_opt6),
				GEO_BRANCH(1, smw_mario_002_switch_opt0_001_switch_opt1_000_switch_opt0_000_switch_001_opt9_switch_face2_opt7),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout smw_mario_002_switch_opt0_001_switch_opt1_000_switch_opt1_switch_face_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, smw_mario_002_switch_option_head__no_cap__mesh_layer_1_mat_override_face_1___eye_half_v3_001_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout smw_mario_002_switch_opt0_001_switch_opt1_000_switch_opt1_switch_face_opt2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, smw_mario_002_switch_option_head__no_cap__mesh_layer_1_mat_override_face_2___eye_closed_v3_001_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout smw_mario_002_switch_opt0_001_switch_opt1_000_switch_opt1_switch_face_opt3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, smw_mario_002_switch_option_head__no_cap__mesh_layer_1_mat_override_face_2___eye_closed_v3_001_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout smw_mario_002_switch_opt0_001_switch_opt1_000_switch_opt1_switch_face_opt4[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, smw_mario_002_switch_option_head__no_cap__mesh_layer_1_mat_override_face_2___eye_closed_v3_001_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout smw_mario_002_switch_opt0_001_switch_opt1_000_switch_opt1_switch_face_opt5[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, smw_mario_002_switch_option_head__no_cap__mesh_layer_1_mat_override_face_2___eye_closed_v3_001_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout smw_mario_002_switch_opt0_001_switch_opt1_000_switch_opt1_switch_face_opt6[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, smw_mario_002_switch_option_head__no_cap__mesh_layer_1_mat_override_face_2___eye_closed_v3_001_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout smw_mario_002_switch_opt0_001_switch_opt1_000_switch_opt1_switch_face_opt7[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, smw_mario_002_switch_option_head__no_cap__mesh_layer_1_mat_override_face_7___eye_X_v3_001_3),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout smw_mario_002_switch_opt0_001_switch_opt1_jump_smw_mario_armature_002_switch_option_002[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 4, 0, 0, 0, 0),
		GEO_OPEN_NODE(),
			GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
			GEO_OPEN_NODE(),
				GEO_NODE_START(),
				GEO_OPEN_NODE(),
					GEO_DISPLAY_LIST(LAYER_TRANSPARENT, smw_mario_002_switch_option_head__no_cap__mesh_layer_1),
				GEO_CLOSE_NODE(),
				GEO_BRANCH(1, smw_mario_002_switch_opt0_001_switch_opt1_000_switch_opt1_switch_face_opt1),
				GEO_BRANCH(1, smw_mario_002_switch_opt0_001_switch_opt1_000_switch_opt1_switch_face_opt2),
				GEO_BRANCH(1, smw_mario_002_switch_opt0_001_switch_opt1_000_switch_opt1_switch_face_opt3),
				GEO_BRANCH(1, smw_mario_002_switch_opt0_001_switch_opt1_000_switch_opt1_switch_face_opt4),
				GEO_BRANCH(1, smw_mario_002_switch_opt0_001_switch_opt1_000_switch_opt1_switch_face_opt5),
				GEO_BRANCH(1, smw_mario_002_switch_opt0_001_switch_opt1_000_switch_opt1_switch_face_opt6),
				GEO_BRANCH(1, smw_mario_002_switch_opt0_001_switch_opt1_000_switch_opt1_switch_face_opt7),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout smw_mario_002_switch_opt0_001_switch_opt1_jump_smw_mario_right_hand_open_armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, smw_mario_002_switch_option_right_hand_open_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout smw_mario_002_switch_opt0_001_switch_opt1_jump_smw_mario_left_hand_open_armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, smw_mario_002_switch_option_left_hand_open_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout smw_mario_002_switch_opt0_001_switch_opt1_jump_smw_mario_left_hand_peace_armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, smw_mario_004_switch_option_left_hand_peace_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout smw_mario_002_switch_opt0_001_switch_opt1_jump_smw_mario_left_hand_cap_armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, smw_mario_005_switch_option_left_hand_cap_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout smw_mario_002_switch_opt0_001_switch_opt1_jump_smw_mario_left_hand_wing_cap_armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, smw_mario_006_switch_option_left_hand_wing_cap_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_TRANSPARENT, smw_mario_006_switch_option_left_hand_wing_cap_wings_mesh_layer_5),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout smw_mario_002_switch_opt0_001_switch_opt1_000_switch_opt0_000_switch_001_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, smw_mario_000_displaylist_mesh_layer_1_mat_override_face_1___eye_half_v3_001_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout smw_mario_002_switch_opt0_001_switch_opt1_000_switch_opt0_000_switch_001_opt2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, smw_mario_000_displaylist_mesh_layer_1_mat_override_face_2___eye_closed_v3_001_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout smw_mario_002_switch_opt0_001_switch_opt1_000_switch_opt0_000_switch_001_opt3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, smw_mario_000_displaylist_mesh_layer_1_mat_override_face_2___eye_closed_v3_001_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout smw_mario_002_switch_opt0_001_switch_opt1_000_switch_opt0_000_switch_001_opt4[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, smw_mario_000_displaylist_mesh_layer_1_mat_override_face_2___eye_closed_v3_001_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout smw_mario_002_switch_opt0_001_switch_opt1_000_switch_opt0_000_switch_001_opt5[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, smw_mario_000_displaylist_mesh_layer_1_mat_override_face_2___eye_closed_v3_001_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout smw_mario_002_switch_opt0_001_switch_opt1_000_switch_opt0_000_switch_001_opt6[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, smw_mario_000_displaylist_mesh_layer_1_mat_override_face_2___eye_closed_v3_001_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout smw_mario_002_switch_opt0_001_switch_opt1_000_switch_opt0_000_switch_001_opt7[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, smw_mario_000_displaylist_mesh_layer_1_mat_override_face_7___eye_X_v3_001_3),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout smw_mario_002_switch_opt0_001_switch_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, smw_mario_000_offset_001_skinned_mesh_layer_1),
				GEO_ASM(0, geo_move_mario_part_from_parent),
				GEO_ASM(0, geo_mario_tilt_torso),
				GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_TRANSPARENT, 25, 0, 0, smw_mario_000_offset_001_mesh_layer_1),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 110, 0, 0, NULL),
						GEO_OPEN_NODE(),
							GEO_ASM(0, geo_mario_head_rotation),
							GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
							GEO_OPEN_NODE(),
								GEO_SWITCH_CASE(0, geo_switch_mario_cap_on_off),
								GEO_OPEN_NODE(),
									GEO_NODE_START(),
									GEO_OPEN_NODE(),
										GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
										GEO_OPEN_NODE(),
											GEO_NODE_START(),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(LAYER_TRANSPARENT, smw_mario_000_displaylist_mesh_layer_1),
											GEO_CLOSE_NODE(),
											GEO_BRANCH(1, smw_mario_002_switch_opt0_001_switch_opt1_000_switch_opt0_000_switch_001_opt1),
											GEO_BRANCH(1, smw_mario_002_switch_opt0_001_switch_opt1_000_switch_opt0_000_switch_001_opt2),
											GEO_BRANCH(1, smw_mario_002_switch_opt0_001_switch_opt1_000_switch_opt0_000_switch_001_opt3),
											GEO_BRANCH(1, smw_mario_002_switch_opt0_001_switch_opt1_000_switch_opt0_000_switch_001_opt4),
											GEO_BRANCH(1, smw_mario_002_switch_opt0_001_switch_opt1_000_switch_opt0_000_switch_001_opt5),
											GEO_BRANCH(1, smw_mario_002_switch_opt0_001_switch_opt1_000_switch_opt0_000_switch_001_opt6),
											GEO_BRANCH(1, smw_mario_002_switch_opt0_001_switch_opt1_000_switch_opt0_000_switch_001_opt7),
											GEO_BRANCH(1, smw_mario_002_switch_opt0_001_switch_opt1_jump_smw_mario_head_faal),
											GEO_BRANCH(1, smw_mario_002_switch_opt0_001_switch_opt1_jump_smw_mario_head_crouch),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
									GEO_BRANCH(1, smw_mario_002_switch_opt0_001_switch_opt1_jump_smw_mario_armature_002_switch_option_002),
								GEO_CLOSE_NODE(),
								GEO_TRANSLATE_ROTATE(LAYER_FORCE, 219, -51, -126, 15, -33, -133),
								GEO_OPEN_NODE(),
									GEO_ASM(0, geo_mario_rotate_wing_cap_wings),
									GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_TRANSPARENT, smw_mario_000_displaylist_001_mesh_layer_5),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
								GEO_TRANSLATE_ROTATE(LAYER_FORCE, 219, -51, 126, -15, 33, -133),
								GEO_OPEN_NODE(),
									GEO_ASM(1, geo_mario_rotate_wing_cap_wings),
									GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_TRANSPARENT, smw_mario_000_displaylist_002_mesh_layer_5),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 82, -25, 85, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, smw_mario_000_offset_003_mesh_layer_1),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_TRANSPARENT, smw_mario_000_offset_004_skinned_mesh_layer_1),
								GEO_ANIMATED_PART(LAYER_TRANSPARENT, 70, 0, 0, smw_mario_000_offset_004_mesh_layer_1),
								GEO_OPEN_NODE(),
									GEO_SWITCH_CASE(1, geo_switch_mario_hand),
									GEO_OPEN_NODE(),
										GEO_NODE_START(),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 55, 0, 0, NULL),
											GEO_OPEN_NODE(),
												GEO_ASM(1, geo_mario_hand_foot_scaler),
												GEO_SCALE(LAYER_FORCE, 65536),
												GEO_OPEN_NODE(),
													GEO_DISPLAY_LIST(LAYER_TRANSPARENT, smw_mario_000_displaylist_003_mesh_layer_1),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_BRANCH(1, smw_mario_002_switch_opt0_001_switch_opt1_jump_smw_mario_right_hand_open_armature),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 83, -25, -85, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, smw_mario_000_offset_006_mesh_layer_1),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_TRANSPARENT, smw_mario_000_offset_007_skinned_mesh_layer_1),
								GEO_ANIMATED_PART(LAYER_TRANSPARENT, 69, 0, 0, smw_mario_000_offset_007_mesh_layer_1),
								GEO_OPEN_NODE(),
									GEO_SWITCH_CASE(0, geo_switch_mario_hand),
									GEO_OPEN_NODE(),
										GEO_NODE_START(),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 56, 0, 0, NULL),
											GEO_OPEN_NODE(),
												GEO_ASM(0, geo_mario_hand_foot_scaler),
												GEO_SCALE(LAYER_FORCE, 65536),
												GEO_OPEN_NODE(),
													GEO_DISPLAY_LIST(LAYER_TRANSPARENT, smw_mario_000_displaylist_004_mesh_layer_1),
												GEO_CLOSE_NODE(),
												GEO_HELD_OBJECT(0, -1, -2, 0, geo_switch_mario_hand_grab_pos),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_BRANCH(1, smw_mario_002_switch_opt0_001_switch_opt1_jump_smw_mario_left_hand_open_armature),
										GEO_BRANCH(1, smw_mario_002_switch_opt0_001_switch_opt1_jump_smw_mario_left_hand_peace_armature),
										GEO_BRANCH(1, smw_mario_002_switch_opt0_001_switch_opt1_jump_smw_mario_left_hand_cap_armature),
										GEO_BRANCH(1, smw_mario_002_switch_opt0_001_switch_opt1_jump_smw_mario_left_hand_wing_cap_armature),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, smw_mario_000_offset_009_skinned_mesh_layer_1),
				GEO_ANIMATED_PART(LAYER_OPAQUE, -16, -5, 42, NULL),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, smw_mario_000_offset_009_mesh_layer_1),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 27, 0, 0, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 18, 0, 0, smw_mario_000_offset_011_mesh_layer_1),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, smw_mario_000_offset_012_skinned_mesh_layer_1),
				GEO_ANIMATED_PART(LAYER_OPAQUE, -16, -5, -42, NULL),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, smw_mario_000_offset_012_mesh_layer_1),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 27, 0, 0, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 18, 0, 0, NULL),
							GEO_OPEN_NODE(),
								GEO_ASM(2, geo_mario_hand_foot_scaler),
								GEO_SCALE(LAYER_FORCE, 65536),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(LAYER_TRANSPARENT, smw_mario_000_displaylist_005_mesh_layer_1),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout smw_mario_002_switch_opt0_001_switch_opt2_jump_smw_mario_head_faal[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 4, 0, 0, 0, 0),
		GEO_OPEN_NODE(),
			GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
			GEO_OPEN_NODE(),
				GEO_NODE_START(),
				GEO_OPEN_NODE(),
					GEO_DISPLAY_LIST(LAYER_OPAQUE, smw_mario_002_switch_option1_headfall_mesh_layer_1_mat_override_METAL_0),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout smw_mario_002_switch_opt0_001_switch_opt2_jump_smw_mario_head_crouch[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 4, 0, 0, 0, 0),
		GEO_OPEN_NODE(),
			GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
			GEO_OPEN_NODE(),
				GEO_NODE_START(),
				GEO_OPEN_NODE(),
					GEO_DISPLAY_LIST(LAYER_OPAQUE, smw_mario_002_switch_option2_headcrouch_mesh_layer_1_mat_override_METAL_0),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout smw_mario_002_switch_opt0_001_switch_opt2_jump_smw_mario_armature_002_switch_option_002[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 4, 0, 0, 0, 0),
		GEO_OPEN_NODE(),
			GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
			GEO_OPEN_NODE(),
				GEO_NODE_START(),
				GEO_OPEN_NODE(),
					GEO_DISPLAY_LIST(LAYER_OPAQUE, smw_mario_002_switch_option_head__no_cap__mesh_layer_1_mat_override_METAL_0),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout smw_mario_002_switch_opt0_001_switch_opt2_jump_smw_mario_right_hand_open_armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, smw_mario_002_switch_option_right_hand_open_mesh_layer_1_mat_override_METAL_0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout smw_mario_002_switch_opt0_001_switch_opt2_jump_smw_mario_left_hand_open_armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, smw_mario_002_switch_option_left_hand_open_mesh_layer_1_mat_override_METAL_0),
		GEO_OPEN_NODE(),
			GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout smw_mario_002_switch_opt0_001_switch_opt2_jump_smw_mario_left_hand_peace_armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, smw_mario_004_switch_option_left_hand_peace_mesh_layer_1_mat_override_METAL_0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout smw_mario_002_switch_opt0_001_switch_opt2_jump_smw_mario_left_hand_cap_armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, smw_mario_005_switch_option_left_hand_cap_mesh_layer_1_mat_override_METAL_0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout smw_mario_002_switch_opt0_001_switch_opt2_jump_smw_mario_left_hand_wing_cap_armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, smw_mario_006_switch_option_left_hand_wing_cap_mesh_layer_1_mat_override_METAL_0),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_TRANSPARENT, smw_mario_006_switch_option_left_hand_wing_cap_wings_mesh_layer_5_mat_override_METAL_0),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout smw_mario_002_switch_opt0_001_switch_opt2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, smw_mario_000_offset_001_skinned_mesh_layer_1_mat_override_METAL_0),
				GEO_ASM(0, geo_move_mario_part_from_parent),
				GEO_ASM(0, geo_mario_tilt_torso),
				GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 25, 0, 0, smw_mario_000_offset_001_mesh_layer_1_mat_override_METAL_0),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 110, 0, 0, NULL),
						GEO_OPEN_NODE(),
							GEO_ASM(0, geo_mario_head_rotation),
							GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
							GEO_OPEN_NODE(),
								GEO_SWITCH_CASE(0, geo_switch_mario_cap_on_off),
								GEO_OPEN_NODE(),
									GEO_NODE_START(),
									GEO_OPEN_NODE(),
										GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
										GEO_OPEN_NODE(),
											GEO_NODE_START(),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(LAYER_OPAQUE, smw_mario_000_displaylist_mesh_layer_1_mat_override_METAL_0),
											GEO_CLOSE_NODE(),
											GEO_BRANCH(1, smw_mario_002_switch_opt0_001_switch_opt2_jump_smw_mario_head_faal),
											GEO_BRANCH(1, smw_mario_002_switch_opt0_001_switch_opt2_jump_smw_mario_head_crouch),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
									GEO_BRANCH(1, smw_mario_002_switch_opt0_001_switch_opt2_jump_smw_mario_armature_002_switch_option_002),
								GEO_CLOSE_NODE(),
								GEO_TRANSLATE_ROTATE(LAYER_FORCE, 219, -51, -126, 15, -33, -133),
								GEO_OPEN_NODE(),
									GEO_ASM(0, geo_mario_rotate_wing_cap_wings),
									GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_TRANSPARENT, smw_mario_000_displaylist_001_mesh_layer_5_mat_override_METAL_0),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
								GEO_TRANSLATE_ROTATE(LAYER_FORCE, 219, -51, 126, -15, 33, -133),
								GEO_OPEN_NODE(),
									GEO_ASM(1, geo_mario_rotate_wing_cap_wings),
									GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_TRANSPARENT, smw_mario_000_displaylist_002_mesh_layer_5_mat_override_METAL_0),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 82, -25, 85, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, smw_mario_000_offset_003_mesh_layer_1_mat_override_METAL_0),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_OPAQUE, smw_mario_000_offset_004_skinned_mesh_layer_1_mat_override_METAL_0),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 70, 0, 0, smw_mario_000_offset_004_mesh_layer_1_mat_override_METAL_0),
								GEO_OPEN_NODE(),
									GEO_SWITCH_CASE(1, geo_switch_mario_hand),
									GEO_OPEN_NODE(),
										GEO_NODE_START(),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 55, 0, 0, NULL),
											GEO_OPEN_NODE(),
												GEO_ASM(1, geo_mario_hand_foot_scaler),
												GEO_SCALE(LAYER_FORCE, 65536),
												GEO_OPEN_NODE(),
													GEO_DISPLAY_LIST(LAYER_OPAQUE, smw_mario_000_displaylist_003_mesh_layer_1_mat_override_METAL_0),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_BRANCH(1, smw_mario_002_switch_opt0_001_switch_opt2_jump_smw_mario_right_hand_open_armature),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 83, -25, -85, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, smw_mario_000_offset_006_mesh_layer_1_mat_override_METAL_0),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_OPAQUE, smw_mario_000_offset_007_skinned_mesh_layer_1_mat_override_METAL_0),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 69, 0, 0, smw_mario_000_offset_007_mesh_layer_1_mat_override_METAL_0),
								GEO_OPEN_NODE(),
									GEO_SWITCH_CASE(0, geo_switch_mario_hand),
									GEO_OPEN_NODE(),
										GEO_NODE_START(),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 56, 0, 0, NULL),
											GEO_OPEN_NODE(),
												GEO_ASM(0, geo_mario_hand_foot_scaler),
												GEO_SCALE(LAYER_FORCE, 65536),
												GEO_OPEN_NODE(),
													GEO_DISPLAY_LIST(LAYER_OPAQUE, smw_mario_000_displaylist_004_mesh_layer_1_mat_override_METAL_0),
												GEO_CLOSE_NODE(),
												GEO_HELD_OBJECT(0, -1, -2, 0, geo_switch_mario_hand_grab_pos),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_BRANCH(1, smw_mario_002_switch_opt0_001_switch_opt2_jump_smw_mario_left_hand_open_armature),
										GEO_BRANCH(1, smw_mario_002_switch_opt0_001_switch_opt2_jump_smw_mario_left_hand_peace_armature),
										GEO_BRANCH(1, smw_mario_002_switch_opt0_001_switch_opt2_jump_smw_mario_left_hand_cap_armature),
										GEO_BRANCH(1, smw_mario_002_switch_opt0_001_switch_opt2_jump_smw_mario_left_hand_wing_cap_armature),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, smw_mario_000_offset_009_skinned_mesh_layer_1_mat_override_METAL_0),
				GEO_ANIMATED_PART(LAYER_OPAQUE, -16, -5, 42, NULL),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, smw_mario_000_offset_009_mesh_layer_1_mat_override_METAL_0),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 27, 0, 0, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 18, 0, 0, smw_mario_000_offset_011_mesh_layer_1_mat_override_METAL_0),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, smw_mario_000_offset_012_skinned_mesh_layer_1_mat_override_METAL_0),
				GEO_ANIMATED_PART(LAYER_OPAQUE, -16, -5, -42, NULL),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, smw_mario_000_offset_012_mesh_layer_1_mat_override_METAL_0),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 27, 0, 0, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 18, 0, 0, NULL),
							GEO_OPEN_NODE(),
								GEO_ASM(2, geo_mario_hand_foot_scaler),
								GEO_SCALE(LAYER_FORCE, 65536),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(LAYER_OPAQUE, smw_mario_000_displaylist_005_mesh_layer_1_mat_override_METAL_0),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout smw_mario_002_switch_opt0_001_switch_opt3_jump_smw_mario_head_faal[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 4, 0, 0, 0, 0),
		GEO_OPEN_NODE(),
			GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
			GEO_OPEN_NODE(),
				GEO_NODE_START(),
				GEO_OPEN_NODE(),
					GEO_DISPLAY_LIST(LAYER_TRANSPARENT, smw_mario_002_switch_option1_headfall_mesh_layer_1_mat_override_METAL_0),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout smw_mario_002_switch_opt0_001_switch_opt3_jump_smw_mario_head_crouch[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 4, 0, 0, 0, 0),
		GEO_OPEN_NODE(),
			GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
			GEO_OPEN_NODE(),
				GEO_NODE_START(),
				GEO_OPEN_NODE(),
					GEO_DISPLAY_LIST(LAYER_TRANSPARENT, smw_mario_002_switch_option2_headcrouch_mesh_layer_1_mat_override_METAL_0),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout smw_mario_002_switch_opt0_001_switch_opt3_jump_smw_mario_armature_002_switch_option_002[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 4, 0, 0, 0, 0),
		GEO_OPEN_NODE(),
			GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
			GEO_OPEN_NODE(),
				GEO_NODE_START(),
				GEO_OPEN_NODE(),
					GEO_DISPLAY_LIST(LAYER_TRANSPARENT, smw_mario_002_switch_option_head__no_cap__mesh_layer_1_mat_override_METAL_0),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout smw_mario_002_switch_opt0_001_switch_opt3_jump_smw_mario_right_hand_open_armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, smw_mario_002_switch_option_right_hand_open_mesh_layer_1_mat_override_METAL_0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout smw_mario_002_switch_opt0_001_switch_opt3_jump_smw_mario_left_hand_open_armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, smw_mario_002_switch_option_left_hand_open_mesh_layer_1_mat_override_METAL_0),
		GEO_OPEN_NODE(),
			GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout smw_mario_002_switch_opt0_001_switch_opt3_jump_smw_mario_left_hand_peace_armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, smw_mario_004_switch_option_left_hand_peace_mesh_layer_1_mat_override_METAL_0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout smw_mario_002_switch_opt0_001_switch_opt3_jump_smw_mario_left_hand_cap_armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, smw_mario_005_switch_option_left_hand_cap_mesh_layer_1_mat_override_METAL_0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout smw_mario_002_switch_opt0_001_switch_opt3_jump_smw_mario_left_hand_wing_cap_armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, smw_mario_006_switch_option_left_hand_wing_cap_mesh_layer_1_mat_override_METAL_0),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_TRANSPARENT, smw_mario_006_switch_option_left_hand_wing_cap_wings_mesh_layer_5_mat_override_METAL_0),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout smw_mario_002_switch_opt0_001_switch_opt3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, smw_mario_000_offset_001_skinned_mesh_layer_1_mat_override_METAL_0),
				GEO_ASM(0, geo_move_mario_part_from_parent),
				GEO_ASM(0, geo_mario_tilt_torso),
				GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_TRANSPARENT, 25, 0, 0, smw_mario_000_offset_001_mesh_layer_1_mat_override_METAL_0),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 110, 0, 0, NULL),
						GEO_OPEN_NODE(),
							GEO_ASM(0, geo_mario_head_rotation),
							GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
							GEO_OPEN_NODE(),
								GEO_SWITCH_CASE(0, geo_switch_mario_cap_on_off),
								GEO_OPEN_NODE(),
									GEO_NODE_START(),
									GEO_OPEN_NODE(),
										GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
										GEO_OPEN_NODE(),
											GEO_NODE_START(),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(LAYER_TRANSPARENT, smw_mario_000_displaylist_mesh_layer_1_mat_override_METAL_0),
											GEO_CLOSE_NODE(),
											GEO_BRANCH(1, smw_mario_002_switch_opt0_001_switch_opt3_jump_smw_mario_head_faal),
											GEO_BRANCH(1, smw_mario_002_switch_opt0_001_switch_opt3_jump_smw_mario_head_crouch),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
									GEO_BRANCH(1, smw_mario_002_switch_opt0_001_switch_opt3_jump_smw_mario_armature_002_switch_option_002),
								GEO_CLOSE_NODE(),
								GEO_TRANSLATE_ROTATE(LAYER_FORCE, 219, -51, -126, 15, -33, -133),
								GEO_OPEN_NODE(),
									GEO_ASM(0, geo_mario_rotate_wing_cap_wings),
									GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_TRANSPARENT, smw_mario_000_displaylist_001_mesh_layer_5_mat_override_METAL_0),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
								GEO_TRANSLATE_ROTATE(LAYER_FORCE, 219, -51, 126, -15, 33, -133),
								GEO_OPEN_NODE(),
									GEO_ASM(1, geo_mario_rotate_wing_cap_wings),
									GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_TRANSPARENT, smw_mario_000_displaylist_002_mesh_layer_5_mat_override_METAL_0),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 82, -25, 85, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, smw_mario_000_offset_003_mesh_layer_1_mat_override_METAL_0),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_TRANSPARENT, smw_mario_000_offset_004_skinned_mesh_layer_1_mat_override_METAL_0),
								GEO_ANIMATED_PART(LAYER_TRANSPARENT, 70, 0, 0, smw_mario_000_offset_004_mesh_layer_1_mat_override_METAL_0),
								GEO_OPEN_NODE(),
									GEO_SWITCH_CASE(1, geo_switch_mario_hand),
									GEO_OPEN_NODE(),
										GEO_NODE_START(),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 55, 0, 0, NULL),
											GEO_OPEN_NODE(),
												GEO_ASM(1, geo_mario_hand_foot_scaler),
												GEO_SCALE(LAYER_FORCE, 65536),
												GEO_OPEN_NODE(),
													GEO_DISPLAY_LIST(LAYER_TRANSPARENT, smw_mario_000_displaylist_003_mesh_layer_1_mat_override_METAL_0),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_BRANCH(1, smw_mario_002_switch_opt0_001_switch_opt3_jump_smw_mario_right_hand_open_armature),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 83, -25, -85, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, smw_mario_000_offset_006_mesh_layer_1_mat_override_METAL_0),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_TRANSPARENT, smw_mario_000_offset_007_skinned_mesh_layer_1_mat_override_METAL_0),
								GEO_ANIMATED_PART(LAYER_TRANSPARENT, 69, 0, 0, smw_mario_000_offset_007_mesh_layer_1_mat_override_METAL_0),
								GEO_OPEN_NODE(),
									GEO_SWITCH_CASE(0, geo_switch_mario_hand),
									GEO_OPEN_NODE(),
										GEO_NODE_START(),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 56, 0, 0, NULL),
											GEO_OPEN_NODE(),
												GEO_ASM(0, geo_mario_hand_foot_scaler),
												GEO_SCALE(LAYER_FORCE, 65536),
												GEO_OPEN_NODE(),
													GEO_DISPLAY_LIST(LAYER_TRANSPARENT, smw_mario_000_displaylist_004_mesh_layer_1_mat_override_METAL_0),
												GEO_CLOSE_NODE(),
												GEO_HELD_OBJECT(0, -1, -2, 0, geo_switch_mario_hand_grab_pos),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_BRANCH(1, smw_mario_002_switch_opt0_001_switch_opt3_jump_smw_mario_left_hand_open_armature),
										GEO_BRANCH(1, smw_mario_002_switch_opt0_001_switch_opt3_jump_smw_mario_left_hand_peace_armature),
										GEO_BRANCH(1, smw_mario_002_switch_opt0_001_switch_opt3_jump_smw_mario_left_hand_cap_armature),
										GEO_BRANCH(1, smw_mario_002_switch_opt0_001_switch_opt3_jump_smw_mario_left_hand_wing_cap_armature),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, smw_mario_000_offset_009_skinned_mesh_layer_1_mat_override_METAL_0),
				GEO_ANIMATED_PART(LAYER_OPAQUE, -16, -5, 42, NULL),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, smw_mario_000_offset_009_mesh_layer_1_mat_override_METAL_0),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 27, 0, 0, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 18, 0, 0, smw_mario_000_offset_011_mesh_layer_1_mat_override_METAL_0),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, smw_mario_000_offset_012_skinned_mesh_layer_1_mat_override_METAL_0),
				GEO_ANIMATED_PART(LAYER_OPAQUE, -16, -5, -42, NULL),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, smw_mario_000_offset_012_mesh_layer_1_mat_override_METAL_0),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 27, 0, 0, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 18, 0, 0, NULL),
							GEO_OPEN_NODE(),
								GEO_ASM(2, geo_mario_hand_foot_scaler),
								GEO_SCALE(LAYER_FORCE, 65536),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(LAYER_TRANSPARENT, smw_mario_000_displaylist_005_mesh_layer_1_mat_override_METAL_0),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout smw_mario_002_switch_opt0_001_switch_opt0_000_switch_opt0_000_switch_001_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, smw_mario_000_displaylist_mesh_layer_1_mat_override_face_1___eye_half_v3_001_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout smw_mario_002_switch_opt0_001_switch_opt0_000_switch_opt0_000_switch_001_opt2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, smw_mario_000_displaylist_mesh_layer_1_mat_override_face_2___eye_closed_v3_001_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout smw_mario_002_switch_opt0_001_switch_opt0_000_switch_opt0_000_switch_001_opt3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, smw_mario_000_displaylist_mesh_layer_1_mat_override_face_2___eye_closed_v3_001_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout smw_mario_002_switch_opt0_001_switch_opt0_000_switch_opt0_000_switch_001_opt4[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, smw_mario_000_displaylist_mesh_layer_1_mat_override_face_2___eye_closed_v3_001_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout smw_mario_002_switch_opt0_001_switch_opt0_000_switch_opt0_000_switch_001_opt5[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, smw_mario_000_displaylist_mesh_layer_1_mat_override_face_2___eye_closed_v3_001_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout smw_mario_002_switch_opt0_001_switch_opt0_000_switch_opt0_000_switch_001_opt6[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, smw_mario_000_displaylist_mesh_layer_1_mat_override_face_2___eye_closed_v3_001_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout smw_mario_002_switch_opt0_001_switch_opt0_000_switch_opt0_000_switch_001_opt7[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, smw_mario_000_displaylist_mesh_layer_1_mat_override_face_7___eye_X_v3_001_3),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout smw_mario_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SHADOW(1, 180, 100),
		GEO_OPEN_NODE(),
			GEO_SCALE(LAYER_FORCE, 16384),
			GEO_OPEN_NODE(),
				GEO_ASM(0, geo_mirror_mario_backface_culling),
				GEO_ASM(0, geo_mirror_mario_set_alpha),
				GEO_SWITCH_CASE(0, smw_small_switch),
				GEO_OPEN_NODE(),
					GEO_NODE_START(),
					GEO_OPEN_NODE(),
						GEO_SWITCH_CASE(0, geo_switch_mario_cap_effect),
						GEO_OPEN_NODE(),
							GEO_NODE_START(),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_OPAQUE, smw_mario_000_offset_001_skinned_mesh_layer_1),
										GEO_ASM(0, geo_move_mario_part_from_parent),
										GEO_ASM(0, geo_mario_tilt_torso),
										GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 25, 0, 0, smw_mario_000_offset_001_mesh_layer_1),
											GEO_OPEN_NODE(),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 110, 0, 0, NULL),
												GEO_OPEN_NODE(),
													GEO_ASM(0, geo_mario_head_rotation),
													GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
													GEO_OPEN_NODE(),
														GEO_SWITCH_CASE(0, geo_switch_mario_cap_on_off),
														GEO_OPEN_NODE(),
															GEO_NODE_START(),
															GEO_OPEN_NODE(),
																GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
																GEO_OPEN_NODE(),
																	GEO_NODE_START(),
																	GEO_OPEN_NODE(),
																		GEO_DISPLAY_LIST(LAYER_OPAQUE, smw_mario_000_displaylist_mesh_layer_1),
																	GEO_CLOSE_NODE(),
																	GEO_BRANCH(1, smw_mario_002_switch_opt0_001_switch_opt0_000_switch_opt0_000_switch_001_opt1),
																	GEO_BRANCH(1, smw_mario_002_switch_opt0_001_switch_opt0_000_switch_opt0_000_switch_001_opt2),
																	GEO_BRANCH(1, smw_mario_002_switch_opt0_001_switch_opt0_000_switch_opt0_000_switch_001_opt3),
																	GEO_BRANCH(1, smw_mario_002_switch_opt0_001_switch_opt0_000_switch_opt0_000_switch_001_opt4),
																	GEO_BRANCH(1, smw_mario_002_switch_opt0_001_switch_opt0_000_switch_opt0_000_switch_001_opt5),
																	GEO_BRANCH(1, smw_mario_002_switch_opt0_001_switch_opt0_000_switch_opt0_000_switch_001_opt6),
																	GEO_BRANCH(1, smw_mario_002_switch_opt0_001_switch_opt0_000_switch_opt0_000_switch_001_opt7),
																	GEO_BRANCH(1, smw_mario_head_faal),
																	GEO_BRANCH(1, smw_mario_head_crouch),
																GEO_CLOSE_NODE(),
															GEO_CLOSE_NODE(),
															GEO_BRANCH(1, smw_mario_armature_002_switch_option_002),
														GEO_CLOSE_NODE(),
														GEO_TRANSLATE_ROTATE(LAYER_FORCE, 219, -51, -126, 15, -33, -133),
														GEO_OPEN_NODE(),
															GEO_ASM(0, geo_mario_rotate_wing_cap_wings),
															GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
															GEO_OPEN_NODE(),
																GEO_DISPLAY_LIST(LAYER_TRANSPARENT, smw_mario_000_displaylist_001_mesh_layer_5),
															GEO_CLOSE_NODE(),
														GEO_CLOSE_NODE(),
														GEO_TRANSLATE_ROTATE(LAYER_FORCE, 219, -51, 126, -15, 33, -133),
														GEO_OPEN_NODE(),
															GEO_ASM(1, geo_mario_rotate_wing_cap_wings),
															GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
															GEO_OPEN_NODE(),
																GEO_DISPLAY_LIST(LAYER_TRANSPARENT, smw_mario_000_displaylist_002_mesh_layer_5),
															GEO_CLOSE_NODE(),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 82, -25, 85, NULL),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, smw_mario_000_offset_003_mesh_layer_1),
													GEO_OPEN_NODE(),
														GEO_DISPLAY_LIST(LAYER_OPAQUE, smw_mario_000_offset_004_skinned_mesh_layer_1),
														GEO_ANIMATED_PART(LAYER_OPAQUE, 70, 0, 0, smw_mario_000_offset_004_mesh_layer_1),
														GEO_OPEN_NODE(),
															GEO_SWITCH_CASE(1, geo_switch_mario_hand),
															GEO_OPEN_NODE(),
																GEO_NODE_START(),
																GEO_OPEN_NODE(),
																	GEO_ANIMATED_PART(LAYER_OPAQUE, 55, 0, 0, NULL),
																	GEO_OPEN_NODE(),
																		GEO_ASM(1, geo_mario_hand_foot_scaler),
																		GEO_SCALE(LAYER_FORCE, 65536),
																		GEO_OPEN_NODE(),
																			GEO_DISPLAY_LIST(LAYER_OPAQUE, smw_mario_000_displaylist_003_mesh_layer_1),
																		GEO_CLOSE_NODE(),
																	GEO_CLOSE_NODE(),
																GEO_CLOSE_NODE(),
																GEO_BRANCH(1, smw_mario_right_hand_open_armature),
															GEO_CLOSE_NODE(),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 83, -25, -85, NULL),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, smw_mario_000_offset_006_mesh_layer_1),
													GEO_OPEN_NODE(),
														GEO_DISPLAY_LIST(LAYER_OPAQUE, smw_mario_000_offset_007_skinned_mesh_layer_1),
														GEO_ANIMATED_PART(LAYER_OPAQUE, 69, 0, 0, smw_mario_000_offset_007_mesh_layer_1),
														GEO_OPEN_NODE(),
															GEO_SWITCH_CASE(0, geo_switch_mario_hand),
															GEO_OPEN_NODE(),
																GEO_NODE_START(),
																GEO_OPEN_NODE(),
																	GEO_ANIMATED_PART(LAYER_OPAQUE, 56, 0, 0, NULL),
																	GEO_OPEN_NODE(),
																		GEO_ASM(0, geo_mario_hand_foot_scaler),
																		GEO_SCALE(LAYER_FORCE, 65536),
																		GEO_OPEN_NODE(),
																			GEO_DISPLAY_LIST(LAYER_OPAQUE, smw_mario_000_displaylist_004_mesh_layer_1),
																		GEO_CLOSE_NODE(),
																		GEO_HELD_OBJECT(0, -1, -2, 0, geo_switch_mario_hand_grab_pos),
																	GEO_CLOSE_NODE(),
																GEO_CLOSE_NODE(),
																GEO_BRANCH(1, smw_mario_left_hand_open_armature),
																GEO_BRANCH(1, smw_mario_left_hand_peace_armature),
																GEO_BRANCH(1, smw_mario_left_hand_cap_armature),
																GEO_BRANCH(1, smw_mario_left_hand_wing_cap_armature),
															GEO_CLOSE_NODE(),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_DISPLAY_LIST(LAYER_OPAQUE, smw_mario_000_offset_009_skinned_mesh_layer_1),
										GEO_ANIMATED_PART(LAYER_OPAQUE, -16, -5, 42, NULL),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, smw_mario_000_offset_009_mesh_layer_1),
											GEO_OPEN_NODE(),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 27, 0, 0, NULL),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(LAYER_OPAQUE, 18, 0, 0, smw_mario_000_offset_011_mesh_layer_1),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_DISPLAY_LIST(LAYER_OPAQUE, smw_mario_000_offset_012_skinned_mesh_layer_1),
										GEO_ANIMATED_PART(LAYER_OPAQUE, -16, -5, -42, NULL),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, smw_mario_000_offset_012_mesh_layer_1),
											GEO_OPEN_NODE(),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 27, 0, 0, NULL),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(LAYER_OPAQUE, 18, 0, 0, NULL),
													GEO_OPEN_NODE(),
														GEO_ASM(2, geo_mario_hand_foot_scaler),
														GEO_SCALE(LAYER_FORCE, 65536),
														GEO_OPEN_NODE(),
															GEO_DISPLAY_LIST(LAYER_OPAQUE, smw_mario_000_displaylist_005_mesh_layer_1),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
							GEO_BRANCH(1, smw_mario_002_switch_opt0_001_switch_opt1),
							GEO_BRANCH(1, smw_mario_002_switch_opt0_001_switch_opt2),
							GEO_BRANCH(1, smw_mario_002_switch_opt0_001_switch_opt3),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
					GEO_BRANCH(1, smw_mario_SMALL_Mario),
				GEO_CLOSE_NODE(),
				GEO_ASM(1, geo_mirror_mario_backface_culling),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, smw_mario_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, smw_mario_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
